#!/usr/bin/env python

import argparse
import json
import os
import pprint
import sys
from slackclient import SlackClient

# Configuration defaults
CONFIG = {
    "channel": "general",
    "emoji": ":robot_face:",
    "token": None,
    "username": "slackerr",
    "verbose": False,
}


def vprint(*args):
    if CONFIG["verbose"]:
        for arg in args:
            print arg,
        print


def send(sc, msg):
    vprint("Sending request:\n%s\n" % pprint.pformat(sc.api_call(
        "chat.postMessage", channel="#%s" % CONFIG["channel"], text=msg,
        username=CONFIG["username"], icon_emoji=CONFIG["emoji"]
    )))


def start():
    # Load configuration from file
    try:
        config_filename = "%s/.slackerr" % os.path.expanduser("~")
        with open(config_filename) as config_file:
            CONFIG.update(json.load(config_file))
    except IOError as e:
        print "Error reading %s: %s" % (config_filename, e.strerror)
        sys.exit(e.errno)

    # Setup argument parsing
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--channel", help="")
    parser.add_argument("-u", "--username", help="")
    # parser.add_argument("-f", "--file", help="") TODO
    parser.add_argument("-v", "--verbose",
                        help="increase output verbosity", action="store_true")
    parser.add_argument("message", help="", nargs='?')

    # Parse command line arguments
    args = vars(parser.parse_args())
    message = args.pop("message")

    # Update configuration and dump
    CONFIG.update({k: v for (k, v) in args.items() if v is not None})
    vprint("Configuration settings:\n%s\n" % pprint.pformat(CONFIG))

    if CONFIG["token"] is None:
        print "Slack API token is missing from config"
        sys.exit(-1)

    # Initialize session
    sc = SlackClient(CONFIG["token"])

    # If the message was provided, send it
    if message is not None:
        send(sc, message)

    # Otherwise, wait for stdin
    else:
        for line in sys.stdin:
            sys.stdout.write(line)
            send(sc, line)

if __name__ == "__main__":
    try:
        start()
    except KeyboardInterrupt:
        pass
